// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkT7w-jpnFTBPAwEmhFREiBCLLhnbRLUc',
    appId: '1:75993923403:web:5b552f4d9f01f74a54f2ce',
    messagingSenderId: '75993923403',
    projectId: 'maazon-6aa57',
    authDomain: 'maazon-6aa57.firebaseapp.com',
    storageBucket: 'maazon-6aa57.appspot.com',
    measurementId: 'G-V0X1Z2BW7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX4w-YUSGZCuBZi_YIARqTPK_9HiEV9RI',
    appId: '1:75993923403:android:62c5cc985551329654f2ce',
    messagingSenderId: '75993923403',
    projectId: 'maazon-6aa57',
    storageBucket: 'maazon-6aa57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9K7_D1pUg16nM0ejOF02xG51vKILqOf4',
    appId: '1:75993923403:ios:769d6268430c590a54f2ce',
    messagingSenderId: '75993923403',
    projectId: 'maazon-6aa57',
    storageBucket: 'maazon-6aa57.appspot.com',
    iosBundleId: 'com.example.maezon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9K7_D1pUg16nM0ejOF02xG51vKILqOf4',
    appId: '1:75993923403:ios:769d6268430c590a54f2ce',
    messagingSenderId: '75993923403',
    projectId: 'maazon-6aa57',
    storageBucket: 'maazon-6aa57.appspot.com',
    iosBundleId: 'com.example.maezon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkT7w-jpnFTBPAwEmhFREiBCLLhnbRLUc',
    appId: '1:75993923403:web:dece4e44d5c0234354f2ce',
    messagingSenderId: '75993923403',
    projectId: 'maazon-6aa57',
    authDomain: 'maazon-6aa57.firebaseapp.com',
    storageBucket: 'maazon-6aa57.appspot.com',
    measurementId: 'G-KFZBC49Q83',
  );
}
