// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5PZnh0CjtjoY0SQyw9zeBy8Ps2-FG82U',
    appId: '1:727111486239:web:322088bfb462d10045fe2a',
    messagingSenderId: '727111486239',
    projectId: 'gwaz-b098e',
    authDomain: 'gwaz-b098e.firebaseapp.com',
    storageBucket: 'gwaz-b098e.appspot.com',
    measurementId: 'G-9P518FVK2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmuNZU1g8-fhr9x-syh-m2v7HLbRSr8nI',
    appId: '1:727111486239:android:f9cc5cd3cb848b0945fe2a',
    messagingSenderId: '727111486239',
    projectId: 'gwaz-b098e',
    storageBucket: 'gwaz-b098e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjDrrxKvQTeahxbIG2xtXVXpeLatZgcD0',
    appId: '1:727111486239:ios:ad5667b97791cea545fe2a',
    messagingSenderId: '727111486239',
    projectId: 'gwaz-b098e',
    storageBucket: 'gwaz-b098e.appspot.com',
    iosBundleId: 'com.example.maezon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjDrrxKvQTeahxbIG2xtXVXpeLatZgcD0',
    appId: '1:727111486239:ios:ad5667b97791cea545fe2a',
    messagingSenderId: '727111486239',
    projectId: 'gwaz-b098e',
    storageBucket: 'gwaz-b098e.appspot.com',
    iosBundleId: 'com.example.maezon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5PZnh0CjtjoY0SQyw9zeBy8Ps2-FG82U',
    appId: '1:727111486239:web:3f9447e9009dc46245fe2a',
    messagingSenderId: '727111486239',
    projectId: 'gwaz-b098e',
    authDomain: 'gwaz-b098e.firebaseapp.com',
    storageBucket: 'gwaz-b098e.appspot.com',
    measurementId: 'G-E5F6EP9WYP',
  );
}
